name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run build script
      run: |
        echo "$PASSWORD" | docker login --username "$USERNAME" --password-stdin "$REGISTRY"
        chmod +x ./build.sh
        ./build.sh
      env:
        REGISTRY: ghcr.io
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    
